name: iOS IPA Build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build Flutter iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.2"
          channel: stable
          cache: true

      - name: Check Flutter
        run: |
          flutter --version
          dart --version

      - name: Enable Swift Package Manager
        run: flutter config --enable-swift-package-manager

      - name: Flutter Clean
        run: flutter clean

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -R build/ios/iphoneos/Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-iOS-IPA
          path: FlutterIpaExport.ipa
